server:
  port: 8001
spring:
  application:
    name: local-grpc-client

grpc:
  client:
    local-grpc-server:
      address: 'static://jobs:8002'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
